### ISSUE TITLE
Support the \additionalaffiliation command

### ISSUE THREAD

**Issue by jozilla** [quarto-journals/acm#29]
The acmart style has the ability to add a footnote for [authors with multiple affiliations](https://ctan.math.illinois.edu/macros/latex/contrib/acmart/acmguide.pdf) using the \additionalaffiliation{} command. It would be great to support this as an option for the author block. In LaTeX, it works as follows:

```
\author{John Doe}
\additionalaffiliation{%
  \institution{Stanford University}
  \city{Stanford}
  \state{CA}
  \country{USA}
}
\affiliation{%
  \institution{Acme, Inc.}
  \city{Chicago} 
  \state{IL} 
  \country{USA}
}
\email{john@stanford.edu}
```

This could be supported in the following way (here, with all authors sharing an affiliation, but the first having an additional affiliation).

```
author:
  - name: John Doe
    email: john@stanford.edu
    additionalaffiliation:
     name: Stanford University
     city: Stanford
     state: CA
     country: USA
  - name: Jeff Wayne
    email: jeff@acme.com
  - name: Emily Riker
    email: emily@acme.com
    affiliation:
      name: Acme, Inc.
      city: Chicago
      state: IL
      country: USA
```

Right now, this doesn't result in an error but also doesn't produce the desired result (there's no footnote added).
