### ISSUE TITLE
The anonymous option in the metadata doesn't do anything

### ISSUE THREAD

**Issue by ulyngs** [quarto-journals/acm#31]
When I set

```yaml
acm-metadata:
  # comment this out to make submission anonymous
  anonymous: true
```

the authors are still all shown
