### ISSUE TITLE
Multiple bib files are not correctly rendered

### ISSUE THREAD

**Issue by jooyoungseo** [quarto-journals/acm#9]
It seems like there is a missing separator in `\bibliography` of this template.

Let's say there are multiple bib files are used like below:

``` yaml

---
format: acm-pdf
bibliography: ["foo.bib", "bar.bib"]
---

```

This produces a tex file with the following output:

`_output.tex`:

``` tex
\bibliography{foo.bibbar.bib}
```
